---
- name: install nginx build dependencies
  apt: pkg="{{ item }}" state=latest
  with_items: nginx_build_dependencies

- name: ensure the build dir exists
  file:
    state: directory
    dest: "{{ nginx_build_dir }}"

- name: check nginx download
  stat: path="{{ nginx_archive }}" get_md5=yes
  register: nginx_download

- name: download nginx
  get_url:
    url: "{{ nginx_download_url }}"
    dest: "{{ nginx_build_dir }}"
    sha256sum: "{{ nginx_download_checksum }}"

- name: extract nginx archive to /tmp
  command: tar -xvf {{ nginx_archive }} -C {{ nginx_build_dir }}

- name: check nginx subs module download
  stat: path="{{ nginx_subs_module_archive }}" get_md5=yes
  register: nginx_subs_module_download

- name: download nginx subs module
  get_url:
    url: "{{ nginx_subs_module_url }}"
    dest: "{{ nginx_subs_module_archive }}"
    sha256sum: "{{ nginx_subs_module_checksum }}"

- name: extract nginx subs module archive to /tmp
  command: tar -xvf {{ nginx_subs_module_archive }} -C {{ nginx_build_dir }}

- name: configure nginx build
  command: chdir={{ nginx_build_dir }}/{{ nginx_version }} ./configure --prefix=/usr/local --with-http_ssl_module --with-pcre --with-http_gzip_static_module --with-http_spdy_module --with-http_gunzip_module --with-http_dav_module --add-module={{ nginx_subs_module_dir }}

- name: build nginx
  command: chdir={{ nginx_build_dir }}/{{ nginx_version }} make

- name: install nginx
  command: chdir={{ nginx_build_dir }}/{{ nginx_version }} make install

- name: add nginx service file
  copy: src=nginx-init dest=/etc/init/nginx.conf owner=root mode=0644

- name: add nginx config
  copy: src=nginx.conf dest=/usr/local/conf/nginx.conf owner=root mode=0644

- name: restart nginx
  command: initctl nginx restart
