---
- name: wait for all tor hidden services hostname files
  wait_for: state=present path="{{ tor_hidden_services_parent_dir }}/{{ item }}/hostname" delay=5
  with_items: app_tor_instances

- name: fetch proxy ths
  fetch: src=/var/lib/tor/services/proxy/hostname dest=./hostname-ths-proxy flat=yes fail_on_missing=yes
