---
# Variables that apply to both the app and monitor server go in this file
# If the monitor or app server need different values define the variable in 
# hosts_vars/app.yml or host_vars/mon.yml host_vars/development.yml
tor_wait_for_hidden_services: yes
tor_hidden_services_parent_dir: "/var/lib/tor/services"
tor_user: debian-tor
tor_DataDirectory: /var/lib/tor

disabled_kernel_modules:
  - bluetooth
  - iwlwifi

ssh_2fa_dependencies:
  - libpam-google-authenticator

sysctl_flags:
  - name: "net.ipv4.tcp_max_syn_backlog"
    value: "4096"
  - name: "net.ipv4.tcp_syncookies"
    value: "1"
  - name: "net.ipv4.conf.all.rp_filter"
    value: "1"
  - name: "net.ipv4.conf.all.accept_source_route"
    value: "0"
  - name: "net.ipv4.conf.all.accept_redirects"
    value: "0"
  - name: "net.ipv4.conf.all.secure_redirects"
    value: "0"
  - name: "net.ipv4.conf.default.rp_filter"
    value: "1"
  - name: "net.ipv4.conf.default.accept_source_route"
    value: "0"
  - name: "net.ipv4.conf.default.accept_redirects"
    value: "0"
  - name: "net.ipv4.conf.default.secure_redirects"
    value: "0"
  - name: "net.ipv4.icmp_echo_ignore_broadcasts"
    value: "1"
  - name: "net.ipv4.ip_forward"
    value: "0"
  - name: "net.ipv4.conf.all.send_redirects"
    value: "0"
  - name: "net.ipv4.conf.default.send_redirects"
    value: "0"
  - name: "net.ipv6.conf.all.disable_ipv6"
    value: "1"
  - name: "net.ipv6.conf.default.disable_ipv6"
    value: "1"
  - name: "net.ipv6.conf.lo.disable_ipv6"
    value: "1"

# grsec vars
grub_pax:
  - /usr/sbin/grub-probe
  - /usr/sbin/grub-mkdevicemap

grsec_package: securedrop-grsec

### Used by the build-nginx role ###
nginx_build_dependencies:
  - libpcre3-dev
  - libssl-dev
  - make
torproxy_dir: "/var/torproxy"
nginx_build_dir: "/var/torproxy/nginx"
nginx_download_url: "http://nginx.org/download/nginx-1.6.2.tar.gz"
nginx_download_checksum: "b5608c2959d3e7ad09b20fc8f9e5bd4bc87b3bc8ba5936a513c04ed8f1391a18"
nginx_download_md5: "d1b55031ae6e4bce37f8776b94d8b930"
nginx_version: "nginx-1.6.2"
nginx_archive: "{{ nginx_build_dir }}/{{ nginx_version }}.tar.gz"

nginx_subs_module_url: "https://github.com/yaoweibin/ngx_http_substitutions_filter_module/archive/v0.6.4.tar.gz"
nginx_subs_module_archive: "{{ nginx_build_dir }}/subs-module.tar.gz"
nginx_subs_module_checksum: "ed4ddbcf0c434f4a1e97b61251a63ace759792764bd5cb79ff20efe348db8db3"
nginx_subs_module_md5: "bc4482c8f9a10a59d14e46693b87e00c"
nginx_subs_module_dir: "{{ nginx_build_dir }}/ngx_http_substitutions_filter_module-0.6.4"
