---
#securedop_repo is defined in site-specific.yml config

### Used by the common role ###
# ssh_users is defined in the site-specific.yml config
# monitor_ip is defined in the site-specific.yml config
# monitor_hostname is defined in the site-specific.yml config

### Used by the app role ###

# Configuring the tor hidden services
app_tor_instances:
  - proxy

apparmor_profiles:
  - usr.sbin.tor
  - usr.sbin.nginx

### Used by the test role ###

direct_access_rules:
  - "-A INPUT -p tcp --dport 22 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  - "-A OUTPUT -p tcp --sport 22 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  - "-A OUTPUT -p udp --dport 53 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  - "-A INPUT -p udp --sport 53 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  - "-A INPUT -p tcp --dport 80 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  - "-A OUTPUT -p tcp --sport 80 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  - "-A INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  - "-A OUTPUT -p tcp --sport 8080 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
